replicaCount: 2

image:
  repository: swapnil0078/nodejs-app
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

ingress:
  enabled: false



